src/kolclient.ts
=> Add check for fruit wastage; account for *hilarious* randomisation of hanged vs hung

src/kolcommands.ts, src/misccommands.ts
This is at @docrostov's suggestion; we can easily edit the exact message text to be easier to deal with
=> create !prswelcome command

src/kolclient.ts, src/kolcommands.ts
I ended up adding off-hand checks and familiar equip checks to this. Adding support for scraping new familiar names makes this a little wobblier; if you don't like it, I can easily roll back that commit.
=> first pass at generalizing the item-spading system

src/wikisearch.ts
It feels like this should be less trivial than it appears
=> rest pizza node before refreshing mafia data

src/kolclient.ts, src/kolcommands.ts, src/things.ts, src/wikisearch.ts
I haven't tested this actual code (not sure how you do that) but I am confident the method works.
=> Add spading for new skills

src/wikisearch.ts
The only issue here is that we're sourcing wiki images but I think that's ok.
=> Find images for more wiki results

src/misccommands.ts
=> Work out correct org for prswelcome

package-lock.json, package.json, src/commands/kol/sombrero.ts, src/commands/misc/index.ts, src/commands/misc/messiah.ts, src/index.ts, src/wikisearch.ts
=> update sombrero.ts and push first iteration of messiah command

src/commands/wiki/mafia.ts
=> Split mafia command into subcommands for wiki and js

src/clients/kol.ts, src/commands/clan/_dread.ts, src/commands/clan/clan.ts, src/commands/clan/skills.ts
- Detect if joining a clan failed and give better error messages if so
- Add autocomplete to /clan slash command
=> Autocomplete the clan names for /clan

src/clients/kol.ts, src/commands/clan/_clans.ts, src/commands/clan/brains.ts, src/commands/clan/skills.ts, src/commands/clan/whitelist.ts
- Allow querying player by name or id
- Whitelist player by name or id
=> whitelist player by id

src/commands/clan/_clans.ts, src/commands/clan/brainiac.ts, src/commands/clan/brains.ts, src/commands/clan/done.ts, src/commands/clan/skills.ts, src/commands/clan/status.ts
I want to do this with everything eventually but this is a quick win.
=> Serve brainiacs directly from db

package-lock.json, package.json, prisma/migrations/20230302130232_create_tags_table/migration.sql, prisma/schema.prisma, src/clients/discord.ts, src/commands/misc/remind.ts, src/commands/misc/tag.ts, src/commands/misc/tagger.ts, src/commands/misc/version.ts, src/commands/wiki/wiki.ts, src/index.ts
- Upgrade prisma
- Setup bot to support modal events
- Use events from enum instead of as strings
- Add message tagging commands
=> Message tagging

src/commands/kol/whois.ts
This change catches names such as `123guy`
=> Match any quantity of digits before a non-digit.

src/clients/kol.ts, src/commands/kol/whois.ts
I've put the icon next to the user's name because that looks nicest to me.
=> Show currently online status for /whois command

src/clients/wiki.ts, src/commands/kol/itemdrop.ts, src/commands/wiki/item.ts, src/commands/wiki/monster.ts, src/things/Item.ts, src/things/Monster.ts
- Filter out bad lines from mafia data
- Fix up some memoizing to clear caches when appropriate
- Add new /item and /monster query commands, rename /item to /itemdrop
=> Enable direct autocompletable queries of specific Things

src/clients/__fixtures__/effects_by_number.html, src/clients/__fixtures__/effects_by_number_100.html, src/clients/__fixtures__/skills_by_number.html, src/clients/wiki.test.ts, src/clients/wiki.ts
- Fix wiki links for skills and any thing with an id under 100
- Add tests for wiki links
=> fix wiki links

src/clients/discord.ts
This isn't triggering, googling suggests that this is likely the issue
=> add appropriate intent for adding the listener role

src/clients/kol.ts, src/commands/kol/announcement.ts
Step one handled here which is that they are now emitted as events on KoLClient
=> Handle system messages

src/commands/kol/crimbowar.ts
One thing I'm not confident about is how the CBC radio messages work; are they "public", will we properly parse the player, etc
=> add a 'crimbowar' function to check the status of the ongoing crimbo war

src/clients/LibreLinkupClient.ts, src/commands/misc/kenny.ts, src/config.ts
Environment variables already locked and loaded.
=> Add important /kenny command

src/clients/pizza.ts, src/clients/wiki.ts
=> Move away from storing all Things together

packages/oaf/src/commands/clan/skills.ts
no idea if this is desirable, but it's an option!
=> switch from a `for` loop to a `reduce` for `participation`

packages/kol.js/src/Client.ts, packages/oaf/package.json, packages/oaf/src/commands/clan/skills.ts, yarn.lock
- **Do full raid parsing clan by clan**
- **Possible better handling of client being suddenly logged out**
- **Move from tsm to tsx**
=> Skill calculation fixes

packages/oaf/src/commands/misc/itom.ts
As requested. I don't actually have the first idea how to actually test this, but the change is small.
=> :minusone: on itoy, too
